stages:
  - mirror_clone

mirror_clone:
  image: bitnami/git
  stage: mirror_clone
  tags: [backend]
  
  before_script:
      - mkdir -p ~/.ssh/
      - echo "$GITHUB_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
      - chmod 700 ~/.ssh/id_rsa
      - eval $(ssh-agent -s)
      - ssh-add ~/.ssh/id_rsa
      - ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
      - cat ~/.ssh/id_rsa.pub
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts
      
  script:
      - git clone https://${GITLAB_TOKEN_NAME}:${GITLAB_TOKEN}@git.appkode.ru/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git 
      - cd ${CI_PROJECT_NAME} && git checkout ${CI_COMMIT_BRANCH} && git filter-branch -f --env-filter "GIT_AUTHOR_NAME='${GIT_AUTHOR_NAME}' GIT_AUTHOR_EMAIL='${GIT_AUTHOR_EMAIL}' GIT_COMMITTER_NAME='${GIT_COMMITER_NAME}' GIT_COMMITTER_EMAIL='${GIT_COMMITTER_EMAIL}'" HEAD
      - git push --mirror -f git@github.com:${GITHUB_USER}/${CI_PROJECT_NAME}.git
      
